[workspace]
resolver = "2"
members = [
	'crates/ort',
	'crates/ort-macros',
	'crates/ort-sys',
	'examples/custom-ops',
	'examples/gpt2',
	'examples/model-info',
	'examples/yolov8',
	'examples/modnet'
]
default-members = [
	'crates/ort',
	'crates/ort-macros',
	'crates/ort-sys',
	'examples/custom-ops',
	'examples/gpt2',
	'examples/model-info',
	'examples/yolov8',
	'examples/modnet'
]

[workspace.package]
version = "2.0.0-rc.0"
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pykeio/ort"
documentation = "https://ort.pyke.io/"
readme = "README.md"
keywords = [ "machine-learning", "ai", "ml" ]
categories = [ "algorithms", "mathematics", "science", "science" ]
authors = [ "pyke.io <contact@pyke.io>" ]

[workspace.dependencies]
ort-sys = { version = "2.0.0-rc.0", path = "crates/ort-sys" }
ort-macros = { version = "2.0.0-rc.0", path = "crates/ort-macros" }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
